from pathlib import Path
import webbrowser
import customtkinter as ctk
from . import ANDROID_API, BUILD_TOOLS
from .core import ANDROID_LICENSE_URL
from .generator import DEFAULT_MAIN
from .ui_theme import ACCENT, BLUE, BORDER, CARD, CARD_ALT, ENTRY, MUTED, PURPLE, SUCCESS, TEXT, WARNING

class LayoutMixin:
    def _tab(self,key): return self.tabs.tab(self._tab_names[key])
    def _section(self,parent,title_key,subtitle_key=None,**values):
        card=ctk.CTkFrame(parent,fg_color=CARD,corner_radius=15,border_width=1,border_color="#152131");card.pack(fill="x",padx=12,pady=10)
        self.trw(ctk.CTkLabel(card,text_color=TEXT,anchor="w",font=ctk.CTkFont(size=16,weight="bold")),title_key).pack(fill="x",padx=18,pady=(15,2))
        if subtitle_key:self.trw(ctk.CTkLabel(card,text_color=MUTED,anchor="w",justify="left",wraplength=1040),subtitle_key,**values).pack(fill="x",padx=18,pady=(0,10))
        body=ctk.CTkFrame(card,fg_color="transparent");body.pack(fill="x",padx=18,pady=(4,16));return body
    def _field(self,parent,key,default="",show=None):
        row=ctk.CTkFrame(parent,fg_color="transparent");row.pack(fill="x",pady=6);self.trw(ctk.CTkLabel(row,width=160,anchor="w",text_color=MUTED),key).pack(side="left")
        entry=ctk.CTkEntry(row,fg_color=ENTRY,border_color=BORDER,text_color=TEXT,show=show);entry.pack(side="left",fill="x",expand=True)
        if default:entry.insert(0,default)
        return entry
    def _home_tab(self):
        tab=self._tab("home");hero=ctk.CTkFrame(tab,fg_color=CARD,corner_radius=18,border_width=1,border_color="#173044");hero.pack(fill="x",padx=14,pady=(14,8))
        self.trw(ctk.CTkLabel(hero,text_color=TEXT,anchor="w",font=ctk.CTkFont(size=24,weight="bold")),"home.title").pack(fill="x",padx=22,pady=(20,4));self.trw(ctk.CTkLabel(hero,text_color=MUTED,anchor="w",justify="left",wraplength=980),"home.subtitle").pack(fill="x",padx=22,pady=(0,18))
        status=ctk.CTkFrame(hero,fg_color="transparent");status.pack(fill="x",padx=22,pady=(0,20));self.home_project_status=self.trw(ctk.CTkLabel(status,fg_color="#10211d",text_color=SUCCESS,corner_radius=10,padx=12,pady=7),"home.project_unknown");self.home_project_status.pack(side="left");self.home_engine_status=self.trw(ctk.CTkLabel(status,fg_color="#221d12",text_color=WARNING,corner_radius=10,padx=12,pady=7),"home.engine_unknown");self.home_engine_status.pack(side="left",padx=10)
        cards=ctk.CTkFrame(tab,fg_color="transparent");cards.pack(fill="x",padx=8,pady=4)
        for column in range(3):cards.grid_columnconfigure(column,weight=1)
        self._home_step(cards,0,"1","home.step1","home.step1_sub","home.open_project",lambda:self._go_tab("project"),BLUE);self._home_step(cards,1,"2","home.step2","home.step2_sub","home.prepare_engine",self.prepare_engine,PURPLE);self._home_step(cards,2,"3","home.step3","home.step3_sub","home.build_now",self.start_build,ACCENT,True)
        note=self._section(tab,"home.zero_setup","home.zero_setup_sub");self.trw(ctk.CTkLabel(note,text_color=MUTED,anchor="w",justify="left",wraplength=1000),"home.zero_setup_detail").pack(fill="x")
    def _home_step(self,parent,column,number,title_key,sub_key,button_key,command,color,dark_text=False):
        card=ctk.CTkFrame(parent,fg_color=CARD,corner_radius=16,border_width=1,border_color="#152131");card.grid(row=0,column=column,sticky="nsew",padx=6,pady=6)
        ctk.CTkLabel(card,text=number,width=34,height=34,corner_radius=17,fg_color=color,text_color="#04100e" if dark_text else TEXT,font=ctk.CTkFont(weight="bold")).pack(anchor="w",padx=16,pady=(16,8));self.trw(ctk.CTkLabel(card,text_color=TEXT,anchor="w",font=ctk.CTkFont(size=17,weight="bold")),title_key).pack(fill="x",padx=16);self.trw(ctk.CTkLabel(card,text_color=MUTED,anchor="w",justify="left",wraplength=300),sub_key).pack(fill="x",padx=16,pady=(5,14));self.trw(ctk.CTkButton(card,fg_color=color,text_color="#04100e" if dark_text else TEXT,command=command),button_key).pack(fill="x",padx=16,pady=(0,16))
    def _project_tab(self):
        body=self._section(self._tab("project"),"project.application","project.application_sub");self.app_name=self._field(body,"project.app_name","Ghost App");self.package_name=self._field(body,"project.package","com.swir.ghostapp");self.icon_path=self._field(body,"project.icon");self.trw(ctk.CTkButton(body,fg_color=CARD_ALT,command=lambda:self._pick_file(self.icon_path,[("Image","*.png *.jpg *.jpeg *.webp")])),"project.browse_icon").pack(anchor="w",padx=(160,0))
        row=ctk.CTkFrame(body,fg_color="transparent");row.pack(fill="x",pady=6);self.trw(ctk.CTkLabel(row,width=160,anchor="w",text_color=MUTED),"project.version").pack(side="left");self.version_name=ctk.CTkEntry(row,width=170,fg_color=ENTRY,border_color=BORDER);self.version_name.insert(0,"1.0.0");self.version_name.pack(side="left");self.version_code=ctk.CTkEntry(row,width=100,fg_color=ENTRY,border_color=BORDER);self.version_code.insert(0,"1");self.version_code.pack(side="left",padx=10)
        out=self._section(self._tab("project"),"project.output","project.output_sub");self.format_var,self.mode_var=ctk.StringVar(value="APK"),ctk.StringVar(value="Debug");choose=ctk.CTkFrame(out,fg_color="transparent");choose.pack(fill="x",pady=5);ctk.CTkSegmentedButton(choose,values=["APK","AAB"],variable=self.format_var,selected_color=ACCENT).pack(side="left");ctk.CTkSegmentedButton(choose,values=["Debug","Release"],variable=self.mode_var,selected_color=BLUE).pack(side="left",padx=12);self.output_dir=self._field(out,"project.output_folder",str(Path.home()/"Desktop"));self.trw(ctk.CTkButton(out,fg_color=CARD_ALT,command=lambda:self._pick_dir(self.output_dir)),"project.browse_output").pack(anchor="w",padx=(160,0))
    def _kotlin_tab(self):
        tab=self._tab("kotlin");ctk.CTkLabel(tab,text="MainActivity.kt",text_color=TEXT,font=ctk.CTkFont(size=16,weight="bold")).pack(anchor="w",padx=14,pady=(12,3));self.trw(ctk.CTkLabel(tab,text_color=MUTED),"kotlin.description").pack(anchor="w",padx=14);self.code=ctk.CTkTextbox(tab,font=("Cascadia Mono",13),fg_color="#060a0f",border_width=1,border_color=BORDER);self.code.pack(fill="both",expand=True,padx=14,pady=12);self.code.insert("1.0",DEFAULT_MAIN)
    def _android_tab(self):
        sdk=self._section(self._tab("android"),"android.target","android.target_sub",api=ANDROID_API,build_tools=BUILD_TOOLS);row=ctk.CTkFrame(sdk,fg_color="transparent");row.pack(fill="x");self.trw(ctk.CTkLabel(row,text_color=MUTED),"android.min_sdk").pack(side="left");self.min_sdk=ctk.CTkEntry(row,width=75);self.min_sdk.insert(0,"24");self.min_sdk.pack(side="left",padx=(8,24));self.trw(ctk.CTkLabel(row,text_color=MUTED),"android.target_sdk").pack(side="left");self.target_sdk=ctk.CTkEntry(row,width=75);self.target_sdk.insert(0,str(ANDROID_API));self.target_sdk.pack(side="left",padx=(8,24));self.trw(ctk.CTkLabel(row,text_color=MUTED),"android.orientation").pack(side="left");self.orientation=ctk.StringVar(value="unspecified");ctk.CTkOptionMenu(row,values=["unspecified","portrait","landscape"],variable=self.orientation).pack(side="left",padx=8)
        perms=self._section(self._tab("android"),"android.permissions","android.permissions_sub");self.internet,self.camera,self.location,self.microphone=ctk.BooleanVar(value=True),ctk.BooleanVar(),ctk.BooleanVar(),ctk.BooleanVar();self.cleartext,self.backup=ctk.BooleanVar(),ctk.BooleanVar()
        for key,var in (("android.internet",self.internet),("android.camera",self.camera),("android.location",self.location),("android.microphone",self.microphone),("android.cleartext",self.cleartext),("android.backup",self.backup)):self.trw(ctk.CTkCheckBox(perms,variable=var,fg_color=ACCENT),key).pack(side="left",padx=(0,14),pady=8)
        runtime=self._section(self._tab("android"),"android.runtime");self.splash,self.fullscreen,self.hardware=ctk.BooleanVar(value=True),ctk.BooleanVar(),ctk.BooleanVar(value=True);self.minify,self.adb_deploy=ctk.BooleanVar(),ctk.BooleanVar()
        for key,var in (("android.splash",self.splash),("android.fullscreen",self.fullscreen),("android.hardware",self.hardware),("android.minify",self.minify),("android.adb",self.adb_deploy)):self.trw(ctk.CTkCheckBox(runtime,variable=var,fg_color=ACCENT),key).pack(side="left",padx=(0,14),pady=8)
        self.assets=self._field(runtime,"project.assets");self.trw(ctk.CTkButton(runtime,fg_color=CARD_ALT,command=lambda:self._pick_dir(self.assets)),"project.browse_assets").pack(anchor="w",padx=(160,0))
    def _signing_tab(self):
        body=self._section(self._tab("signing"),"signing.title","signing.subtitle");self.signing=ctk.BooleanVar();self.trw(ctk.CTkCheckBox(body,variable=self.signing,fg_color=ACCENT),"signing.enable").pack(anchor="w",pady=(0,8));self.keystore=self._field(body,"signing.keystore");self.trw(ctk.CTkButton(body,fg_color=CARD_ALT,command=lambda:self._pick_file(self.keystore,[("Java Keystore","*.jks *.keystore")])),"signing.browse").pack(anchor="w",padx=(160,0));self.alias=self._field(body,"signing.alias","ghost_key");self.store_password=self._field(body,"signing.store_password",show="•");self.key_password=self._field(body,"signing.key_password",show="•");self.trw(ctk.CTkButton(body,fg_color=PURPLE,command=self.generate_keystore),"signing.generate").pack(anchor="w",padx=(160,0),pady=8);self.trw(ctk.CTkLabel(body,text_color=MUTED,wraplength=760,justify="left"),"signing.notice").pack(anchor="w",padx=(160,0))
    def _engine_tab(self):
        body=self._section(self._tab("engine"),"engine.title","engine.subtitle");self.engine_text=ctk.CTkTextbox(body,height=245,fg_color="#060a0f",font=("Cascadia Mono",12));self.engine_text.pack(fill="x",pady=(0,12));self.engine_text.configure(state="disabled");row=ctk.CTkFrame(body,fg_color="transparent");row.pack(fill="x");self.trw(ctk.CTkButton(row,fg_color=CARD_ALT,command=self.refresh_engine_status),"engine.refresh").pack(side="left");self.trw(ctk.CTkButton(row,fg_color=ACCENT,text_color="#04100e",command=self.prepare_engine),"engine.prepare").pack(side="left",padx=10);self.trw(ctk.CTkButton(row,fg_color=PURPLE,command=self.repair_engine),"engine.repair").pack(side="left");self.trw(ctk.CTkButton(row,fg_color=CARD_ALT,command=lambda:webbrowser.open(ANDROID_LICENSE_URL)),"engine.terms").pack(side="right");self.trw(ctk.CTkLabel(body,text_color=MUTED),"engine.privacy").pack(fill="x",pady=(12,0))
    def _logs_tab(self):
        tab=self._tab("logs");row=ctk.CTkFrame(tab,fg_color="transparent");row.pack(fill="x",padx=14,pady=(12,4));self.trw(ctk.CTkLabel(row,text_color=TEXT,font=ctk.CTkFont(size=16,weight="bold")),"logs.title").pack(side="left");self.trw(ctk.CTkButton(row,width=100,fg_color=CARD,command=self._copy_logs),"logs.copy").pack(side="right");self.trw(ctk.CTkButton(row,width=100,fg_color=CARD,command=self._clear_logs),"logs.clear").pack(side="right",padx=8);self.trw(ctk.CTkButton(row,width=100,fg_color=CARD,command=self._export_logs),"logs.export").pack(side="right");self.logs=ctk.CTkTextbox(tab,font=("Cascadia Mono",12),fg_color="#05080c");self.logs.pack(fill="both",expand=True,padx=14,pady=(4,14));self.logs.configure(state="disabled")
